### ISSUE TITLE
No Such File Or Directory 

### ISSUE THREAD

**Issue by vatsalpatels** [WangXuhongCN/myGNN#1]
Hi Xuhong,

I hope you're doing well. I wanted to seek help with the below error which I'm facing while running main.py file:

**Error:** "FileNotFoundError: [Errno 2] No such file or directory: '/floyd/home/log/cora+OC-GAE.log'"

**This is what I'm trying to run:** python main.py --dataset cora --module GAE --gpu 0 --n-epochs 5000  --seed 46

Looking like the path given to read the log file isn't correct because of which it shows no such file or directory. Can you check if you are also able to replicate this bug?

![Screen Shot 2020-06-21 at 2 39 19 pm](https://user-images.githubusercontent.com/50659626/85225833-2d91d180-b417-11ea-86c7-d6e009bc649f.png)

Best Regards,
Vatsal Patel

**Comment by WangXuhongCN** [comment]
Thanks for your issue. It has a simple solution: just create a folder named "log" in the root directory (which means you shall create a "log" folder in the same directory as ”main.py“.).  BTW, I guess you also need to create another folder named "checkpoints".

**Comment by vatsalpatels** [comment]
Thank you for your quick reply. That worked perfectly for me :)
