### ISSUE TITLE
**ERROR: cannot find key: --dataset**

### ISSUE THREAD

**Issue by vatsalpatels** [WangXuhongCN/myGNN#2]
I'm facing another error that I wanted to bring to your attention. I'm working on this error too but wanted to drop a message to see if you know what's happening here.

**ERROR: cannot find key: --dataset**

![image](https://user-images.githubusercontent.com/50659626/85726695-ad7eab00-b739-11ea-835a-f353ec008c83.png)

**Comment by WangXuhongCN** [comment]
I assume you've modified the code to fit your own dataset? I can review your code to find out where the problem is.

**Comment by vatsalpatels** [comment]
I'm sorry for missing out to mention that I'm running using the same dataset. I'm yet to modify the data loader to fit my own data. This is what I'm currently running. Regardless of any model, it's showing the above error.

python main.py --dataset cora --module GCN --gpu 0 --n-epochs 5000  --seed 46

**Comment by WangXuhongCN** [comment]
> I'm sorry for missing out to mention that I'm running using the same dataset. I'm yet to modify the data loader to fit my own data. This is what I'm currently running. Regardless of any model, it's showing the above error.
> 
> python main.py --dataset cora --module GCN --gpu 0 --n-epochs 5000 --seed 46

I don't know why this error happens, but I think this error has no effect on the result of the code, the output of the code will be stored in the log file.

**Comment by vatsalpatels** [comment]
You are right, it really doesn’t have any impact on the results and I’m still able to store the output in the log file. I think that’s what I need for now and I’m almost finished working on fitting my data in the data loader. I will let you know if I need any other help.
